# Cloudflare Workers configuration for BlockchainVibe Assets
name = "blockchainvibe-assets"
main = "assets-worker.js"
compatibility_date = "2024-01-01"

# R2 Bucket binding for file storage
[[r2_buckets]]
bucket_name = "blockchainvibe-assets"
binding = "blockchainvibe_assets"
