# Cloudflare Workers configuration for BlockchainVibe
name = "blockchainvibe-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
NODE_ENV = "production"
JWT_SECRET = "your-jwt-secret-key-here"
GOOGLE_CLIENT_ID = "your-google-client-id"
GOOGLE_CLIENT_SECRET = "your-google-client-secret"
GITHUB_CLIENT_ID = "your-github-client-id"
GITHUB_CLIENT_SECRET = "your-github-client-secret"
TWITTER_CLIENT_ID = "your-twitter-client-id"
TWITTER_CLIENT_SECRET = "your-twitter-client-secret"
DISCORD_CLIENT_ID = "1431187449215717457"
DISCORD_CLIENT_SECRET = "d3QI-oClsHiCTFPumMkQ8OWwAaJ5O8us"

# D1 Database binding (will be created)
[[d1_databases]]
binding = "DB"
database_name = "blockchainvibe-db"
database_id = "4d7784cc-f73a-4d7d-a108-fc283cc21916"

# R2 Bucket binding for file storage
[[r2_buckets]]
bucket_name = "blockchainvibe-assets"
binding = "blockchainvibe_assets"